baseURL = "https://breadth.app/article/"
languageCode = "zh-CN"
title = "市场宽度 -  Article"
theme = "maupassant"
uglyurls = true

[permalinks]
post = "/:year/:month/:day/:filename"

[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

[menu]
#[[menu.main]]
#identifier = "archives"
#name = "归档"
#url = "/archives/"
#weight = 2
#   [[menu.main]]
#     identifier = "Main"
#     name = "主站"
#     url = "/breadth.app"
#     weight = 2
#
#   [[menu.main]]
#     identifier = "about"
#     name = "关于"
#     url = "/about/"
#     weight = 4

[[params.links]]
  title = "主站"
  name = "Market Breadth"
  url = "https://breadth.app"
[author]
name = "papok"
[params]
subtitle = "Market Breadth"
keywords = "市场宽度,美股市场宽度,Market Breadth,breadth.app,LEI & LoneCapital,技术指标,雷公市场宽度,市场宽度计算"
description = "breadth.app,这里是看美股市场宽度的网站，市场全景，每天更新; U.S. stock market, updated daily，雷公市场宽度"
googleAnalytics = "G-XJLPLKGPCG"
author = "papok"
fancybox = true
# 默认是70
# summaryLength = 140
